name: Build and Publish Extension

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install mise
      uses: jdx/mise-action@v2
      
    - name: Install dependencies
      run: mise run install
      
    - name: Run tests
      run: npm test
      
    - name: Build extension package
      run: mise run package
      
    - name: Upload extension artifact
      uses: actions/upload-artifact@v4
      with:
        name: vsix-package
        path: "*.vsix"
        retention-days: 30

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install mise
      uses: jdx/mise-action@v2
      
    - name: Install dependencies
      run: mise run install
      
    - name: Build extension package
      run: mise run package
      
    - name: Publish to Visual Studio Marketplace
      run: npx @vscode/vsce publish --packagePath *.vsix
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
